name: CD - Statocles

on: 
  push:
    branches:
      - main

jobs:
  perl-job:
    runs-on: ['ubuntu-latest']
    container:
      image: perl
    strategy:
      fail-fast: true
    name: build and publish 
    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          cpanm --notest --verbose Carton
          carton install
      - name: Run buildscript
        run: |
          ./build.sh
      - name: Push rendered files to branch
        run: |
          cp -a .git rendered/.git/
          cd rendered/
          git symbolic-ref HEAD refs/heads/published
          git reset
          git add -A .
          git config --local user.email 'automated@example.com'
          git config --local user.name  'Github actions'
          git commit -m 'Update rendered site'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'published'
          directory: 'rendered/'
          force: true
