name: CD - Statocles

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    pull_request:

jobs:
  perl-job:
    runs-on: ['ubuntu-latest']
    container:
      image: perl
    strategy:
      fail-fast: true
    name: build and publish 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        name: Do checkout
      - name: Setup Perl environment
        run: |
          echo PERL5LIB="$(pwd)/lib:$(pwd)/local/lib/perl5${PERL5LIB:+:PERL5LIB}" >> $GITHUB_ENV
          echo PERL_VERSION="$(perl -E 'print $^V')" >> $GITHUB_ENV
          cat .env >> $GITHUB_ENV
          echo "$(pwd)/local/bin" >> $GITHUB_PATH
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch --track ${{ env.PUBLISH_BRANCH }} origin/${{ env.PUBLISH_BRANCH }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: local
          key: ${{ runner.os }}-cache-deps-${{ env.PERL_VERSION }}-{{ hashFiles('cpanfile') }}
      - name: Get dependencies
        run: |
          cpanm --notest --verbose Carton
          carton install
      - name: Build site for PR
        if: github.event.name == "pull_request" && github.base_ref == "refs/heads/${{ env.SITE_BRANCH }}"
        run: |
          cd site/
          statocles --lib build
      - name: Publish site
        if: github.ref == "refs/heads/${{ env.SITE_BRANCH }}"
        run: |
          git stash -u
          cd site/
          statocles --lib deploy
