name: CD - Statocles

on: 
  push:
    branches:
      - main

jobs:
  perl-job:
    runs-on: ['ubuntu-latest']
    container:
      image: perl
    strategy:
      fail-fast: true
    name: build and publish 
    steps:
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          cpanm --notest --verbose Carton
          carton install
      - name: Run buildscript
        run: |
          ./build.sh
      - name: Push rendered files to branch
        run: |
          cp ../.git rendered/.git/
          cd rendered/
          git symbolic-ref HEAD refs/heads/published
          git reset
          git status
